### ISSUE TITLE
Opencv not cache

### ISSUE THREAD

**Issue by huy-lv** [rayandrews/with-opencv-action#1]
Hello, i setup this tool with these lines, but it does not cache opencv, it downloads opencv everytime i push to master, please help
```
    - name: With OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:
        dir: /opt/minus/libs/opencv-4.5.2
        cached: ${{ steps.opencv-cache.outputs.cache-hit }}
        opencv-version: '4.5.2'
```
